### ISSUE TITLE
network map not requested

### ISSUE THREAD

**Issue by JanJaapKo** [kovainfo/Domoticz-zigbee2mqtt-network-map#1]
Hi,

Something seems to be wrong with the setup, since it only shows exaclty the same picture as in your example (see at the bottom).

Some things I did which might be added to your setup:
- go to Setup > Settings > Other and in the section EventSystem make sure the check-box ‘dzVents enabled’ is checked (default off)
- go to Setup > Settings > System > Local Networks (no username/password) to allow 127.0.0.1 to not need a password

Now having done that, I can trigger the dzEvent by calling the URL: 
http://<my_ip>:8080/json.htm?type=command&param=customevent&event=CreateZigbeeMap
I see the event being logged in domoticz log, all fine. When I click on the button on the Zigbee custom page, same thing. Event is triggered.

But having log open on Zigbee2Mqtt I do not see the message being published, nor a response (which is of course to be expected when nothing published)

When I enter in a command terminal manually the network map command, I do see a response coming into Zigbee2mqtt:
`mosquitto_pub -h localhost -t zigbee2mqtt/bridge/networkmap -m 'raw'`

Then, I pasted the output of this command into the raw.json file. Still no different figure, only this:

![image](https://user-images.githubusercontent.com/44156144/79018402-09db2100-7b74-11ea-85b9-62040b9fc481.png)

**Comment by kovainfo** [comment]
Thanks for the addition to the setup instructions. 
What operating system do you have for Domotikz server?
Do you have mosquitto clients installed?
Does the zigbeemap.sh script have rights for execute?

perhaps you need to additionally refresh the page with the picture. the browser caches data and what it shows at the moment - it may just be a cache.

**Comment by JanJaapKo** [comment]
Sorry, forgot to mention that:
- RPi 3B
- Raspian Buster
- Domoticz latest development (build 11925)
- I have mosquito client installed (hence was able to publish commands from command line)
- I did all mentioned steps on your instruction page, so set the execute rights for .sh script 
- I did refresh/cache refresh a couple of times

I suspect something to go wrong with the .sh script since nothing gets published to the mqtt broker.

![image](https://user-images.githubusercontent.com/44156144/79037936-a4b81780-7bd5-11ea-9f26-ffdffa7a270a.png)

**Comment by kovainfo** [comment]
and still the problem looks like an uncleaned cache.
try open zigbeemap.html directly:
http://<my_ip>:8080/templates/zigbeemap/zigbeemap.html

**Comment by JanJaapKo** [comment]
OK, the cache is 1 thing indeed: in direct acces I do get my own network map displayed from the contents in the raw.json file. 

But there is no message published on the topic `zigbee2mqtt/bridge/networkmap`. When I put back the original raw.json file, it sticks to that. No way to get it updated to my network layout

**Comment by kovainfo** [comment]
it is not necessary to put the original json back. he is there just for demonstration)

**Comment by JanJaapKo** [comment]
@kovainfo as I understood the working the output of `zigbeemap.sh` is saved in the `raw.json` file which is in its turn picked up by `zigbeemap\zigbeemap.html`. So as long as the json file isn't changed by the output of the networkmap result of zigbee2mqtt, I will not get an updated picture, right?

**Comment by kovainfo** [comment]
@JanJaapKo absolutely!

**Comment by kovainfo** [comment]
on the last version of this template, I removed automatically creating a map, because during the networkmap scan your network will be not/less responsive. Depending on the size of your network this can take somewhere between 10 seconds and 2 minutes. Therefore it is recommended to only trigger these scans manually:

https://www.zigbee2mqtt.io/information/mqtt_topics_and_message_structure.html#zigbee2mqttbridgenetworkmap

for creating a map is nessesary push the button on bottom left corner of template page.
